name: Build and Deploy WebGL 🚀

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Project 🛠️
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
          lfs: true
      
      - name: Cache Library 💾
        uses: actions/cache@v3
        with:
          path: src/Library
          key: Library-src-WebGL-${{ github.sha }}
          restore-keys: |
            Library-src-WebGL-
            Library-
          
      - name: Build Unity WebGL 🏗️
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          # UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: src 
          buildName: Game
          targetPlatform: WebGL
          unityVersion: 6000.3.0f1
       
      - name: Prepare Artifact 📂
        run: |
          DEST="build"
          # Copy files
          cp $GITHUB_WORKSPACE/thanks.html $DEST/
          cp $GITHUB_WORKSPACE/thanks.jpg $DEST/
          cp $GITHUB_WORKSPACE/web.config $DEST/
          cp $GITHUB_WORKSPACE/index.html $DEST/
          
          # Copy folders 
          [ -d "$GITHUB_WORKSPACE/css" ] && cp -r $GITHUB_WORKSPACE/css $DEST/
          [ -d "$GITHUB_WORKSPACE/js" ] && cp -r $GITHUB_WORKSPACE/js $DEST/
          
          echo "Final build structure:"
          ls -R $DEST
          
      - name: Upload Build Artifact 📦
        uses: actions/upload-artifact@v4
        with:
          name: PWA-Build
          path: build/WebGL
  deploy:
    name: Deploy to GitHub Pages 🌐
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write # so  actions can write to gh-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: PWA-Build
          path: public

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages
          clean: true #Solve the Dirty Branch
