name: Build and Deploy WebGL 🚀

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Project 🛠️
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
          lfs: true
      
      - name: Cache Library 💾
        uses: actions/cache@v3
        with:
          path: src/Library
          key: Library-src-WebGL-${{ github.sha }}
          restore-keys: |
            Library-src-WebGL-
            Library-
          
      - name: Build Unity WebGL 🏗️
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          # UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: src 
          buildName: Game
          targetPlatform: WebGL
          unityVersion: 6000.3.0f1
       
      - name: Prepare Artifact 📂
        run: |
          # 1. Gain ownership of the build folder
          # Unity (Docker) created this as root, so we need to take it back
          sudo chown -R $USER:$USER build/
          
          # 2. Define target (Make sure it matches your Unity Build output)
          # If Unity builds to build/WebGL, use that.
          DEST="build/WebGL"
          mkdir -p $DEST
          
          # 3. Copy with case-insensitivity check
          # This will find the file regardless of "thanks.html" or "Thanks.html"
          find $GITHUB_WORKSPACE -maxdepth 1 -iname "thanks.html" -exec cp {} $DEST/ \;
          find $GITHUB_WORKSPACE -maxdepth 1 -iname "thanks.jpg" -exec cp {} $DEST/ \;
          find $GITHUB_WORKSPACE -maxdepth 1 -iname "web.config" -exec cp {} $DEST/ \;
          find $GITHUB_WORKSPACE -maxdepth 1 -iname "index.html" -exec cp {} $DEST/ \;
          
          # Copy folders if they exist (case-insensitive)
          find $GITHUB_WORKSPACE -maxdepth 1 -type d -iname "css" -exec cp -r {} $DEST/ \;
          find $GITHUB_WORKSPACE -maxdepth 1 -type d -iname "js" -exec cp -r {} $DEST/ \;
          
          echo "**** Final build structure in $DEST: *****"
          ls -R $DEST
          
      - name: Upload Build Artifact 📦
        uses: actions/upload-artifact@v4
        with:
          name: PWA-Build
          path: build/WebGL
  deploy:
    name: Deploy to GitHub Pages 🌐
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write # so  actions can write to gh-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: PWA-Build
          path: public

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages
          clean: true #Solve the Dirty Branch
